{{- if eq .Values.agent.scope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if eq .Release.Namespace "vessl" }}
  name: vessl
  {{- else }}
  name: vessl-{{ .Release.Namespace }}
  {{- end }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
