apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if eq .Release.Namespace "vessl" }}
  name: vessl
  {{- else }}
  name: vessl-{{ .Release.Namespace }}
  {{- end }}
rules:
  - apiGroups: ["*"]
    {{- if eq .Values.agent.scope "cluster" }}
    resources: ["*"]
    {{- else }}
    resources: ["nodes", "persistentvolumes", "ingressclasses", "services", "priorityclasses"]
    {{- end }}
    verbs: ["*"]
