{{- if index .Values "prometheus-remote-write" "enabled" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ index .Values "prometheus-remote-write" "server" "configMapOverrideName" }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
{{ index .Values "prometheus-remote-write" "server" "global" | toYaml | trimSuffix "\n" | indent 6 }}
    {{- if index .Values "prometheus-remote-write" "server" "remoteWrite" }}
    remote_write:
{{ index .Values "prometheus-remote-write" "server" "remoteWrite" | toYaml | indent 4 }}
    {{- end }}
    scrape_configs:
    - job_name: vessl-dcgm
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - action: keep
        source_labels:
        - __meta_kubernetes_service_annotation_v1_k8s_vessl_ai_type
        - __meta_kubernetes_service_annotationpresent_v1_k8s_vessl_ai_type
        regex: (dcgm-exporter);true
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: metrics
        replacement: $1
        action: keep
{{ toYaml (index .Values "prometheus-remote-write" "relabelConfigs") | nindent 6 }}
      - source_labels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        target_label: nodename
        replacement: $1
        action: replace
      - separator: ;
        regex: feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: label_feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: minikube_(.+)
        replacement: $1
        action: labeldrop
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        modulus: 1
        target_label: __tmp_hash
        replacement: $1
        action: hashmod
      - source_labels: [__tmp_hash]
        separator: ;
        regex: "0"
        replacement: $1
        action: keep
      metric_relabel_configs:
      - separator: ;
        regex: ^(Hostname|instance)$
        replacement: $1
        action: labeldrop
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
        namespaces:
          names: 
          - {{ .Release.Namespace }}
    - job_name: vessl-kube-state-metrics
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - action: keep
        source_labels:
        - __meta_kubernetes_service_annotation_v1_k8s_vessl_ai_type
        - __meta_kubernetes_service_annotationpresent_v1_k8s_vessl_ai_type
        regex: (kube-state-metrics);true
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: http
{{ toYaml (index .Values "prometheus-remote-write" "relabelConfigs") | nindent 6 }}
      - separator: ;
        regex: feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: label_feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: minikube_(.+)
        replacement: $1
        action: labeldrop
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        modulus: 1
        target_label: __tmp_hash
        replacement: $1
        action: hashmod
      - source_labels: [__tmp_hash]
        separator: ;
        regex: "0"
        replacement: $1
        action: keep
      metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: (kube_pod_container_resource_requests|kube_pod_container_resource_limits|kube_node_status_capacity|kube_node_status_allocatable|kube_persistentvolume_(.+)|kube_persistentvolumeclaim_(.+)|kube_pod_status_phase|kube_pod_info|kube_pod_labels|kube_deployment_labels|kube_deployment_status_(.+))
        replacement: $1
        action: keep
      - source_labels: [node]
        separator: ;
        regex: ^(.*)$
        target_label: nodename
        replacement: $1
        action: replace
      - separator: ;
        regex: ^instance$
        replacement: $1
        action: labeldrop
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
        namespaces:
          names: 
          - {{ .Release.Namespace }}
    - job_name: vessl-model-service-servicemonitor
      honor_labels: true
      kubernetes_sd_configs:
      - role: endpoints
      metrics_path: /metrics
      relabel_configs:
      - source_labels:
        - job
        target_label: __tmp_prometheus_job_name
      - action: keep
        source_labels:
        - __meta_kubernetes_service_label_v1_k8s_vessl_ai_serving_metrics_enabled
        - __meta_kubernetes_service_labelpresent_v1_k8s_vessl_ai_serving_metrics_enabled
        regex: (true);true
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: metrics
{{ toYaml (index .Values "prometheus-remote-write" "relabelConfigs") | nindent 6 }}
      - source_labels:
        - __address__
        target_label: __tmp_hash
        modulus: 1
        action: hashmod
      - source_labels:
        - __tmp_hash
        regex: 0
        action: keep
      metric_relabel_configs:
      - source_labels:
        - __name__
        regex: (bentoml_(.+)|BENTOML_(.+)|nv_(.+)|)
        action: keep
    - job_name: vessl-node-exporter-servicemonitor
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - action: keep
        source_labels:
        - __meta_kubernetes_service_annotation_v1_k8s_vessl_ai_type
        - __meta_kubernetes_service_annotationpresent_v1_k8s_vessl_ai_type
        regex: (node-exporter);true
{{ toYaml (index .Values "prometheus-remote-write" "relabelConfigs") | nindent 6 }}
      - source_labels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        target_label: nodename
        replacement: $1
        action: replace
      - separator: ;
        regex: feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: label_feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: minikube_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: ^pod$
        replacement: $1
        action: labeldrop
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        modulus: 1
        target_label: __tmp_hash
        replacement: $1
        action: hashmod
      - source_labels: [__tmp_hash]
        separator: ;
        regex: "0"
        replacement: $1
        action: keep
      metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: (node_filesystem_avail_bytes|node_filesystem_size_bytes|node_ethtool_info|node_network_info|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_network_route_info)
        replacement: $1
        action: keep
      - separator: ;
        regex: ^instance$
        replacement: $1
        action: labeldrop
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
        namespaces:
          names: 
          - {{ .Release.Namespace }}
    - job_name: kubernetes-nodes-kubelet
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: kubernetes.default.svc:443
        action: replace
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        action: replace
      - separator: ;
        regex: (.*)nvidia_com_gfd_timestamp
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: label_feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: minikube_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: nvidia_com_(.+)
        replacement: $1
        action: labeldrop
      - source_labels: [instance]
        separator: ;
        regex: ^(.*)$
        target_label: nodename
        replacement: $1
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: (kubelet_volume_stats_used_bytes|kubelet_volume_stats_capacity_bytes)
        replacement: $1
        action: keep
      kubernetes_sd_configs:
      - role: node
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
    - job_name: kubernetes-nodes-cadvisor
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: kubernetes.default.svc:443
        action: replace
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        action: replace
      - separator: ;
        regex: (.*)nvidia_com_gfd_timestamp
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: label_feature_node_kubernetes_io_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: minikube_(.+)
        replacement: $1
        action: labeldrop
      - separator: ;
        regex: nvidia_com_(.+)
        replacement: $1
        action: labeldrop
      - source_labels: [instance]
        separator: ;
        regex: ^(.*)$
        target_label: nodename
        replacement: $1
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: (container_cpu_usage_seconds_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_memory_working_set_bytes|container_fs_usage_bytes)
        replacement: $1
        action: keep
      kubernetes_sd_configs:
      - role: node
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
{{- end -}}