apiVersion: v2
name: vessl
type: application
version: 0.0.37
appVersion: "0.6.24"
dependencies:
- name: node-feature-discovery
  version: "0.15.4"
  alias: nfd
  condition: nfd.enabled
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
- name: gpu-feature-discovery
  version: "0.8.2"
  alias: gfd
  condition: gfd.enabled
  repository: https://nvidia.github.io/gpu-feature-discovery
- name: kube-state-metrics
  version: "5.19.0"
  condition: kube-state-metrics.enabled
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-node-exporter
  alias: node-exporter
  version: "4.33.0"
  condition: node-exporter.enabled
  repository: https://prometheus-community.github.io/helm-charts
- name: dcgm-exporter
  version: "3.4.1"
  condition: dcgm-exporter.enabled
  repository: https://nvidia.github.io/dcgm-exporter/helm-charts
- name: nvidia-device-plugin
  version: "0.15.0"
  condition: nvidia-device-plugin.enabled
  repository: https://nvidia.github.io/k8s-device-plugin
- name: prometheus
  alias: prometheus-remote-write
  version: "23.2.0"
  condition: prometheus-remote-write.enabled
  repository: https://prometheus-community.github.io/helm-charts
- name: longhorn
  version: "1.5.1"
  condition: longhorn.enabled
  repository: https://charts.longhorn.io
- name: local-path-provisioner
  version: "0.0.24"
  condition: local-path-provisioner.enabled
- name: harbor
  version: "1.0.1"
  condition: harbor.enabled
- name: prometheus-adapter
  version: "4.9.0"
  condition: prometheus-adapter.enabled
  repository: https://prometheus-community.github.io/helm-charts
- name: image-prepull
  version: "0.1.0"
  condition: image-prepull.enabled
