


prometheus-remote-write:
  enabled: true
  server:
    serverFiles:
      prometheus:
        scrape_configs:
          - job_name: vessl-dcgm
            honor_labels: true
            honor_timestamps: true
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            follow_redirects: true
            enable_http2: true
            relabel_configs:
            - source_labels: [job]
              separator: ;
              regex: (.*)
              target_label: __tmp_prometheus_job_name
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              separator: ;
              regex: metrics
              replacement: $1
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Node;(.*)
              target_label: node
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Pod;(.*)
              target_label: pod
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_namespace]
              separator: ;
              regex: (.*)
              target_label: namespace
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: service
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_name]
              separator: ;
              regex: (.*)
              target_label: pod
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_name]
              separator: ;
              regex: (.*)
              target_label: container
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: job
              replacement: ${1}
              action: replace
            - separator: ;
              regex: (.*)
              target_label: endpoint
              replacement: metrics
              action: replace
            - source_labels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              target_label: nodename
              replacement: $1
              action: replace
            - separator: ;
              regex: feature_node_kubernetes_io_(.+)
              replacement: $1
              action: labeldrop
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              modulus: 1
              target_label: __tmp_hash
              replacement: $1
              action: hashmod
            - source_labels: [__tmp_hash]
              separator: ;
              regex: "0"
              replacement: $1
              action: keep
            metric_relabel_configs:
            - separator: ;
              regex: ^(Hostname|instance)$
              replacement: $1
              action: labeldrop
            kubernetes_sd_configs:
            - role: endpoints
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              namespaces:
                own_namespace: false
                names:
                - vessl
          - job_name: vessl-kube-state-metrics
            honor_labels: true
            honor_timestamps: true
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            follow_redirects: true
            enable_http2: true
            relabel_configs:
            - source_labels: [job]
              separator: ;
              regex: (.*)
              target_label: __tmp_prometheus_job_name
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Node;(.*)
              target_label: node
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Pod;(.*)
              target_label: pod
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_namespace]
              separator: ;
              regex: (.*)
              target_label: namespace
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: service
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_name]
              separator: ;
              regex: (.*)
              target_label: pod
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_name]
              separator: ;
              regex: (.*)
              target_label: container
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: job
              replacement: ${1}
              action: replace
            - separator: ;
              regex: (.*)
              target_label: endpoint
              replacement: metrics
              action: replace
            - separator: ;
              regex: feature_node_kubernetes_io_(.+)
              replacement: $1
              action: labeldrop
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              modulus: 1
              target_label: __tmp_hash
              replacement: $1
              action: hashmod
            - source_labels: [__tmp_hash]
              separator: ;
              regex: "0"
              replacement: $1
              action: keep
            metric_relabel_configs:
            - source_labels: [__name__]
              separator: ;
              regex: (kube_pod_container_resource_requests|kube_pod_container_resource_limits|kube_node_status_capacity|kube_node_status_allocatable|kube_persistentvolume_(.+)|kube_persistentvolumeclaim_(.+)|kube_pod_status_phase|kube_pod_info|kube_pod_labels)
              replacement: $1
              action: keep
            - source_labels: [node]
              separator: ;
              regex: ^(.*)$
              target_label: nodename
              replacement: $1
              action: replace
            - separator: ;
              regex: ^instance$
              replacement: $1
              action: labeldrop
            kubernetes_sd_configs:
            - role: endpoints
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              namespaces:
                own_namespace: false
                names:
                - vessl # 수정 필요  
          - job_name: serviceMonitor/vessl/vessl-node-exporter-servicemonitor/0
            honor_labels: true
            honor_timestamps: true
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            follow_redirects: true
            enable_http2: true
            relabel_configs:
            - source_labels: [job]
              separator: ;
              regex: (.*)
              target_label: __tmp_prometheus_job_name
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Node;(.*)
              target_label: node
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Pod;(.*)
              target_label: pod
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_namespace]
              separator: ;
              regex: (.*)
              target_label: namespace
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: service
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_name]
              separator: ;
              regex: (.*)
              target_label: pod
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_name]
              separator: ;
              regex: (.*)
              target_label: container
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: job
              replacement: ${1}
              action: replace
            - separator: ;
              regex: (.*)
              target_label: endpoint
              replacement: metrics
              action: replace
            - source_labels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              target_label: nodename
              replacement: $1
              action: replace
            - separator: ;
              regex: feature_node_kubernetes_io_(.+)
              replacement: $1
              action: labeldrop
            - separator: ;
              regex: ^pod$
              replacement: $1
              action: labeldrop
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              modulus: 1
              target_label: __tmp_hash
              replacement: $1
              action: hashmod
            - source_labels: [__tmp_hash]
              separator: ;
              regex: "0"
              replacement: $1
              action: keep
            metric_relabel_configs:
            - source_labels: [__name__]
              separator: ;
              regex: (node_filesystem_avail_bytes|node_filesystem_size_bytes|node_ethtool_info|node_network_info|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_network_route_info)
              replacement: $1
              action: keep
            - separator: ;
              regex: ^instance$
              replacement: $1
              action: labeldrop
            kubernetes_sd_configs:
            - role: endpoints
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              namespaces:
                own_namespace: false
                names:
                - vessl
          - job_name: kubernetes-nodes-kubelet
            honor_timestamps: true
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: https
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            follow_redirects: true
            enable_http2: true
            relabel_configs:
            - separator: ;
              regex: __meta_kubernetes_node_label_(.+)
              replacement: $1
              action: labelmap
            - separator: ;
              regex: (.*)
              target_label: __address__
              replacement: kubernetes.default.svc:443
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              separator: ;
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              action: replace
            - separator: ;
              regex: (.*)nvidia_com_gfd_timestamp
              replacement: $1
              action: labeldrop
            - separator: ;
              regex: feature_node_kubernetes_io_(.+)
              replacement: $1
              action: labeldrop
            - separator: ;
              regex: nvidia_com_(.+)
              replacement: $1
              action: labeldrop
            - source_labels: [instance]
              separator: ;
              regex: ^(.*)$
              target_label: nodename
              replacement: $1
              action: replace
            metric_relabel_configs:
            - source_labels: [__name__]
              separator: ;
              regex: (kubelet_volume_stats_used_bytes|kubelet_volume_stats_capacity_bytes)
              replacement: $1
              action: keep
            kubernetes_sd_configs:
            - role: node
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
          - job_name: kubernetes-nodes-cadvisor
            honor_timestamps: true
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: https
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            follow_redirects: true
            enable_http2: true
            relabel_configs:
            - separator: ;
              regex: __meta_kubernetes_node_label_(.+)
              replacement: $1
              action: labelmap
            - separator: ;
              regex: (.*)
              target_label: __address__
              replacement: kubernetes.default.svc:443
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              separator: ;
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              action: replace
            - separator: ;
              regex: (.*)nvidia_com_gfd_timestamp
              replacement: $1
              action: labeldrop
            - separator: ;
              regex: feature_node_kubernetes_io_(.+)
              replacement: $1
              action: labeldrop
            - separator: ;
              regex: nvidia_com_(.+)
              replacement: $1
              action: labeldrop
            - source_labels: [instance]
              separator: ;
              regex: ^(.*)$
              target_label: nodename
              replacement: $1
              action: replace
            metric_relabel_configs:
            - source_labels: [__name__]
              separator: ;
              regex: (container_cpu_usage_seconds_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_memory_working_set_bytes|container_fs_usage_bytes)
              replacement: $1
              action: keep
            kubernetes_sd_configs:
            - role: node
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true