{{- if .Values.daemonSet.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hostpath-csi-driver.fullname" . }}-provisioner
  labels:
    {{- include "hostpath-csi-driver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hostpath-csi-driver.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ .Values.daemonSet.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }} 