kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hostpath-csi-driver.fullname" . }}-provisioner-cfg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hostpath-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.daemonSet.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "hostpath-csi-driver.fullname" . }}-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io