{{- if .Values.statefulSet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostpath-csi-driver.fullname" . }}-socat-service
  labels:
    {{- include "hostpath-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: socat
spec:
  type: {{ .Values.statefulSet.service.type }}
  selector:
    {{- include "hostpath-csi-driver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: socat
  ports:
    - port: {{ .Values.statefulSet.service.port }}
      targetPort: {{ .Values.statefulSet.service.port }}
      protocol: TCP
      name: socat
{{- end }}