{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.vesslHostpathDevice.name }}
  labels:
    {{- include "hostpath-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: storageclass
    storage-class: hostpath
  {{- with .Values.storageClass.vesslHostpathDevice.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.storageClass.vesslHostpathDevice.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ .Values.global.driverName }}
volumeBindingMode: {{ .Values.storageClass.vesslHostpathDevice.volumeBindingMode }}
{{- if .Values.storageClass.vesslHostpathDevice.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.storageClass.vesslHostpathDevice.allowVolumeExpansion }}
{{- end }}
{{- if .Values.storageClass.vesslHostpathDevice.reclaimPolicy }}
reclaimPolicy: {{ .Values.storageClass.vesslHostpathDevice.reclaimPolicy }}
{{- end }}
{{- end }}
