{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.priorityClass.name }}
value: {{ .Values.priorityClass.value | int | toYaml }}
description: |
  Used by overprovisioner.
  Pods with this priority class can be evicted (preempted) to yield resources
  whenever workload pods need to be scheduled.
{{- end }}
