apiVersion: v2
name: registry-cache
description: Proxy cache for OCI-based registry.
type: application

version: 0.3.0
appVersion: 0.0.1

dependencies:
- name: harbor
  version: 1.15.0
  repository: 'https://helm.goharbor.io'
  condition: harbor.enabled
