apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.config_map_name }}
data:
  config.json: |-
    {{- include "lpp_advanced_config.config_json_content" . | fromYaml | toPrettyJson | nindent 4 }}

{{- if .Values.xfs_quota.enabled }}
  setup: |-
    {{- $.Files.Get "files/xfs_quota_setup.sh" | nindent 4 }}

  teardown: |-
    {{- $.Files.Get "files/xfs_quota_teardown.sh" | nindent 4 }}

  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
        - name: helper-pod
          image: debian:stable-slim
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
          - name: data
            mountPath: /opt/local-path-provisioner
            mountPropagation: Bidirectional
          - name: fstab
            mountPath: /etc/fstab
            readOnly: true
      volumes:
      - name: fstab
        hostPath:
          path: /etc/fstab
          type: FileOrCreate

{{- else }}
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"

  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"

  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
        - name: helper-pod
          image: quay.io/vessl-ai/busybox:21.10
          imagePullPolicy: IfNotPresent
{{- end }}
