{{- if .Values.zot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cache-zot-config # fixed name; refer to values.yaml
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {{- include "registry_cache.zot_config_yaml" . | fromYaml | toPrettyJson | nindent 4 }}
{{- end }}