{{- with .Values.registryCache.untaint }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount | toString | toYaml }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}