apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-image-prepull
spec:
  selector:
    matchLabels:
      app: image-prepull
  template:
    metadata:
      labels:
        app: image-prepull
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- range .Values.images }}
        {{- $imageName := .name }}
        {{- range .tags }}
      - name: pull-{{ $imageName }}-{{ . | replace ":" "-" | replace "." "-" }}
        image: {{ $imageName }}:{{ . }}
        command: ['sh', '-c', 'echo Image {{ $imageName }}:{{ . }} pulled']
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        {{- end }}
      {{- end }}
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2