name: Release Charts

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Add dependency chart repos
        run: |
          helm repo add node-feature-discovery https://kubernetes-sigs.github.io/node-feature-discovery/charts
          helm repo add gpu-feature-discovery https://nvidia.github.io/gpu-feature-discovery
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add dcgm-exporter https://nvidia.github.io/dcgm-exporter/helm-charts
          helm repo add nvidia-k8s-device-plugin https://nvidia.github.io/k8s-device-plugin

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
